// Generated by https://quicktype.io

export interface GetDailyProgressCheckRes {
    message:   string;
    data:      Datum[];
    limit:     number;
    totalRows: number;
    totalPage: number;
    nextPage:  number;
    prevPage:  number;
}

export interface Datum {
    id:                  string;
    shift:               string;
    pic:                 string;
    inspection_date:     null | Date;
    part_weight_qis:     null | string;
    lot_production:      null | string;
    checked_by:          null | string;
    label_no:            null | string;
    accept_sample_time:  null | Date;
    measure_sample_time: null | Date;
    actual_part_weight:  null | string;
    judgement:           string;
    judgement_3d:        string;
    judgement_2d:        string;
    updated_at:          Date;
    part:                Part;
    machine:             Machine;
}

export interface Machine {
    id:         string;
    id_machine: string;
    no:         string;
}

export interface Part {
    id:              string;
    cust_item_cd:    string;
    part_name:       string;
    part_cd:         string;
    item_group_cd:   string;
    item_group_name: string;
    old_part_number: string;
    unit_cd:         string;
    product_weight:  number;
    customer_model:  CustomerModel;
}

export interface CustomerModel {
    id:   string;
    name: string;
}
