// Generated by https://quicktype.io

export interface ShowDailyProgressCheckRes {
    message: string;
    data:    Data;
}

export interface Data {
    id:                  string;
    shift:               string;
    pic:                 string;
    inspection_date:     Date;
    part_weight_qis:     string;
    lot_production:      string;
    checked_by:          null;
    label_no:            number;
    accept_sample_time:  Date;
    measure_sample_time: Date;
    actual_part_weight:  number;
    judgement:           string;
    judgement_3d:        string;
    judgement_2d:        string;
    part:                Part;
    machine:             Machine;
}

export interface Machine {
    id:         string;
    id_machine: string;
    no:         string;
}

export interface Part {
    id:                   string;
    cust_item_cd:         string;
    part_name:            string;
    part_cd:              string;
    item_group_cd:        string;
    item_group_name:      string;
    old_part_number:      string;
    unit_cd:              string;
    product_weight:       number;
    customer_model:       Customer;
    customer:             Customer;
    customer_model_group: Customer;
    material:             Material;
}

export interface Customer {
    id:   string;
    name: string;
}

export interface Material {
    id:          string;
    id_material: string;
    detail:      string;
    color:       Color;
}

export interface Color {
    id:       string;
    id_color: string;
    name:     string;
}
