// Generated by https://quicktype.io

export interface UpdateDailyProgressCheckReq {
    shift:               string;
    pic:                 string;
    part_cd:             string;
    id_machine:          string;
    inspection_date:     Date;
    part_weight_qis:     string;
    lot_production:      string;
    label_no:            string;
    accept_sample_time:  string;
    measure_sample_time: string;
    actual_part_weight:  string;
}
